// TODO: vervang deze 21 dummy-namen door de echte ledenlijst van JKZ
export const leden = [
  "Dummy 01 Anne de Vries",
  "Dummy 02 Bob Janssen",
  "Dummy 03 Charlotte Smit",
  "Dummy 04 David van den Berg",
  "Dummy 05 Emma Visser",
  "Dummy 06 Frank de Boer",
  "Dummy 07 Giulia van Dijk",
  "Dummy 08 Hendrik Bakker",
  "Dummy 09 Iris Meijer",
  "Dummy 10 Jasper de Groot",
  "Dummy 11 Kim van Leeuwen",
  "Dummy 12 Lars Willems",
  "Dummy 13 Manon Peters",
  "Dummy 14 Niels Hendriks",
  "Dummy 15 Olivia van der Berg",
  "Dummy 16 Pieter Mulder",
  "Dummy 17 Quinty Hofman",
  "Dummy 18 Ruben Kok",
  "Dummy 19 Stephanie Dekker",
  "Dummy 20 Tim van Santen",
  "Dummy 21 Vera Brouwer",
];
