// Plagerige teksten op het scorescherm, per scoreband — met knipogen naar
// de leden en hun bedrijven. Per band wordt er per keer willekeurig één
// gekozen, dus wie vaak speelt ziet steeds een andere.
// 'vanaf' is de minimale score voor die band. Zelf regels toevoegen of
// aanpassen mag altijd: gewoon een regel erbij tussen de aanhalingstekens.
export const PLAAGTEKSTEN = [
  { vanaf: 100, teksten: [
    'Wat een score! Oneted plakt ’m op een billboard zodat iedereen het ziet.',
    'Honderd punten. Duisdecker zet er z’n handtekening onder en noemt het zijn ontwerp.',
    'Honderd punten, vlekkeloos gelegd. Zelfs Van der Laan krijgt z’n vloeren niet zó strak.',
    'De volle honderd! Dit is precies wat Van der Heide bedoelde met Game Changers.',
    'Drie sterren van de voorzitter. Level uitgespeeld!',
    'Honderd punten. Als er een Daan Bolding Award voor scores bestond, hing jouw naam nu ingelijst aan de muur.',
    'Honderd punten. Hier kan zelfs de reiscommissie geen naheffing meer op sturen.',
  ]},
  { vanaf: 80, teksten: [
    'Wauw, wat een score — jij staat vol in de spotlights van Nils!',
    'Sterke score! Patrick Bos is trots — nu dit niveau nog even in de sportschool halen.',
    'Topscore! Bijna net zoveel punten als Sven scoorde bij z’n Colombiaanse scharrel in Barcelona.',
    'Voor deze score staan zelfs Peppi en Kokki (Nils en Bos) op. Tegelijk, zoals altijd.',
    'Deze score zet je zó bovenaan in Google — zonder ook maar één factuur van Jesse. Knap.',
    'Deze score gaat boven de vraagprijs weg — en Binnerts hoefde er niet eens bij te overdrijven.',
    'Deze score is zo strak als een spuitlaag van Kalfsvel Coating. Geen krasje op te bekennen.',
    'Dik rendement op je punten. Hugo belt morgen om je een beleggingsrekening aan te smeren.',
    'Van side quest naar main quest — deze score mag zo het jaarplan in.',
    '“Wow, dit was echt vet geregeld”, zegt penningmeester Stam over jouw score. Missie geslaagd.',
    'Je scheurt over de ranglijst alsof Rainbow Road tóch in de Zaanstreek ligt.',
    'Een score om nooit te vergeten — net als Kenia. Alleen word jij morgen niet wakker met zebra’s voor het raam.',
    'Deze score gaat viral. Straks schrijft de burgemeester er nog een column over.',
    'Deze score is Grand Cru: complex, gelaagd en van uitzonderlijke kwaliteit. Proost.',
    'Business class-score. De rest van de Kamer zit met hun punten gewoon in de economy.',
  ]},
  { vanaf: 60, teksten: [
    'Deze score is een prima fundering, zegt Van der Heide. Oplevering van de top 3 wel pas Q3 2027.',
    'Goed bezig — je bent nog maar een paar punten (en één borrel van Hallatu) verwijderd van de top.',
    'Deze score is een prima loods, maar nog geen penthouse. Mileway zet ’m morgen in de verhuur.',
    'Van Velze tekent zo een huurcontract voor deze score. Wel eentje met indexatie — er moet nog wat bij.',
    'Je score draait als een machine van Camiel. Alleen de bougies nog afstellen voor de volle honderd.',
    'Kars heeft de kleine lettertjes van je score gecheckt: rechtsgeldig. Maar meer zat er echt niet in.',
    'Je score brandt als een ketel van Wessels. Kan alleen nog wel een graadje warmer.',
    'Prima checkpoint, deze score. Even bijladen en door naar het volgende level.',
    'Sven noteert deze score netjes in de notulen. Wees blij — hij vergeet weleens iemand “per ongeluk”.',
    'Deze score is de chocoladeletter, de negen ton komt nog. Blijven spelen dus!',
    'Deze score is als Taxi Binnerts: je komt een heel eind, maar nét niet tot Schiphol.',
  ]},
  { vanaf: 40, teksten: [
    'Matig, matig… deze score kan wel wat optimalisatie gebruiken. Bel Jesse maar eens voor tips.',
    'Deze score is als het busje van Lust Catering: hij kwam ergens, maar niet heelhuids.',
    'Deze score is meer lucht dan inhoud. Tuf Tuf Ballonnen belt al over de rechten.',
    'Deze score is als een verkiezingsbelofte: klonk mooi, viel tegen. Fidel weet precies van welke partij.',
    'De Vastgoeddokter heeft naar je score gekeken. De uitslag: chronisch, maar behandelbaar. Nog een potje?',
    'Op deze score zit garantie tot de deur. En dat terwijl Binnerts nota bene Garantiemakelaar is.',
    'Van Velze geeft deze score hooguit een flexplek. Geen vast contract.',
    'Duisdecker over deze score: de bouwtekening was prima, de uitvoering… tja.',
    'Deze score: veel rook, geen vuurwerk. En geloof me, Nils kent het verschil.',
    'Punten strooien met Zaanse zuinigheid — Stam knikt goedkeurend, maar meer ook niet.',
    'Volgens Kars is deze score “ruim voldoende”. Maar ja, Kars heeft ook de statuten als nachtlectuur.',
    'Deze score is pure Banana Chaos, maar dan zonder de fun. Reflexen trainen en opnieuw!',
    'De Big Five gespot? Deze score haalt niet eens de fotorol van de Keniareis.',
    'Deze score heeft nieuwjaarsborrel-op-oudjaarsdag-logica: het klopt nét niet, maar gezellig was het wel.',
    'Een gok wagen mag van de GOK-Award. Maar deze score bewijst: gokken is geen strategie.',
    'Deze score is als de ETA van de reiscommissie: “bijna rond”. Al drie weken.',
    'Deze score heeft Hangjas Award-potentie: voorlopig even niks, maar op het laatste moment kan het zomaar groots worden.',
    'Deze score is een onafgerond dossier. En zonder onafgeronde dossiers ben je geen echte commissie — dus nog een potje.',
  ]},
  { vanaf: 20, teksten: [
    'Tsjonge jonge, wat een drama — deze score is zo laag als de rente bij de ING.',
    'Au. Je punten lekken weg als een cv-ketel van Wessels.',
    'De top 3? Die is Miles away.',
    'Zo wordt het niks. Vraag Bremer even om een donatie voor extra bonuspunten.',
    'Deze score is één grote black-out. En die stond níet in het lichtplan van Nils.',
    'Je score is door de vloer gezakt. En Boudewijn kan pas over drie weken een nieuwe komen leggen.',
    'Van Velze heeft je score getaxeerd: leegstand.',
    'Zelfs Thijs krijgt deze score niet verkocht. En die verkoopt álles.',
    'Je puntensaldo staat rood. Hugo blokkeert je pas uit voorzorg.',
    'Veel beloofd, weinig punten binnengekomen — Fidel noemt dat een linkse begroting.',
    'Sven overweegt z’n lidmaatschap alwéér op te zeggen na het zien van deze score.',
    'Deze score haalt de doelstelling niet. En die lag al op “minstens zes nieuwe leden”.',
    'Game over op een side quest. En de main quest moet nog beginnen…',
    'Jouw puntenoverzicht is als het jaaroverzicht van Broadcast: kort en overzichtelijk. Want leeg.',
    'De nieuwe eindbaas Joustra heeft deze score gezien, hè.',
    'Zelfs Danny Vera kan deze score niet meer redden.',
    'Deze score verdient de Pleegzuster Bloedwijn Award: duidelijk toe aan een oppepper.',
    '“De portemonnee kan thuisblijven”, zei de reiscommissie. Voor deze score kun je hem beter juist pakken: 1 euro = 1 punt.',
  ]},
  { vanaf: 0, teksten: [
    'Deze score is een drama. Lijkt Patrick Stam in de sportschool wel.',
    'Je score is total loss. Erger dan het busje van Lust Catering, en dat wil wat zeggen.',
    'Deze score is onbewoonbaar verklaard door de Vastgoeddokter. Slopen en opnieuw beginnen.',
    'Zelfs Peppi en Kokki hadden hier meer punten gehaald. En die moeten álles met z’n tweeën.',
    'Kars heeft naar je score gekeken: kansloos. Zelfs in hoger beroep.',
    'Erdi maakt prullenbakken voor precies dit soort scores.',
    'Deze score heeft tien minuten met de zwaartekracht staan discussiëren — en dik verloren.',
    'Zelfs het stamhoofd keek pas na drie kwartier op z’n smartwatch. Bij deze score al na tien seconden.',
    'Hallatu schenkt er eentje in. Niet om te vieren — om deze score te vergeten.',
    'Voor deze score is er een troostprijs: baklava van Ozgur. Die is tenminste wél zoet.',
    'Duisdecker heeft een vakterm voor deze score: bouwval.',
    'Zó plat als deze score krijgt zelfs Tuf Tuf een ballon niet.',
    'Press Start, zei Van der Heide. Deze score is toch echt Press Stop.',
    'Sven schrijft je na deze score uit de ledenlijst. Je merkt het waarschijnlijk niet eens.',
    'Deze score valt onder “falen” uit het jaarplan. Gelukkig stond erbij: samen winnen komt later.',
    'Zelfs de anaconda van Fidel deinst terug voor deze score.',
    'Game over? Zeker niet, zou de voorzitter zeggen. Continue!',
    'Deze score is een echte N.O.O.M.: om een ondeugdelijke reden veel te vroeg opgehouden.',
    'Even gestrekt gaan liggen na deze score? Thijs kan het je uitleggen — die won er de Corona Award mee.',
    'Deze score is net als het JKZ-archief: ergens heel veilig opgeborgen. Zó veilig dat niemand hem kan vinden.',
    'Je kunt een hoop met AI, zegt de CoCo. Maar deze score rechtpraten lukt zelfs de computer niet.',
  ]},
];
