// Plagerige teksten op het scorescherm, per scoreband — met knipogen naar
// de leden en hun bedrijven. Per band wordt er per keer willekeurig één
// gekozen, dus wie vaak speelt ziet steeds een andere.
// 'vanaf' is de minimale score voor die band. Zelf regels toevoegen of
// aanpassen mag altijd: gewoon een regel erbij tussen de aanhalingstekens.
export const PLAAGTEKSTEN = [
  { vanaf: 100, teksten: [
    'Wat een score! Oneted plakt ’m op een billboard zodat iedereen het ziet.',
    'Honderd punten. Duisdecker zet er z’n handtekening onder en noemt het zijn ontwerp.',
    'Vlekkeloos. Zelfs Van der Laan legt z’n vloeren niet zó strak.',
    'LEVEL UP! Dit is precies wat Van der Heide bedoelde met Game Changers.',
    'Drie sterren van de voorzitter. Level uitgespeeld!',
  ]},
  { vanaf: 80, teksten: [
    'Wauw, wat een score — jij staat vol in de spotlights van Nils!',
    'Patrick Bos zou trots op je zijn. Haal dit ook eens in de sportschool!',
    'Topscore! Bijna net zoveel punten als Sven scoorde bij z’n Colombiaanse scharrel in Barcelona.',
    'Zelfs Peppi en Kokki (Nils en Bos) staan hiervoor op. Tegelijk, zoals altijd.',
    'Bovenaan in Google, zonder ook maar één factuur van Jesse. Knap.',
    'Verkocht boven de vraagprijs — en Binnerts hoefde er niet eens bij te overdrijven.',
    'Zo strak als een spuitlaag van Kalfsvel Coating. Geen krasje op te bekennen.',
    'Dik rendement. Hugo probeert je morgen een beleggingsrekening aan te smeren.',
    'Van side quest naar main quest — deze score mag zo het jaarplan in.',
    '“Wow, dit was echt vet geregeld”, zegt penningmeester Stam. Missie geslaagd.',
    'Je scheurt over de ranglijst alsof Rainbow Road tóch in de Zaanstreek ligt.',
    'Onvergetelijk, net als Kenia. Alleen word jij morgen niet wakker met zebra’s voor het raam.',
    'Deze score gaat viral. Straks schrijft de burgemeester er nog een column over.',
  ]},
  { vanaf: 60, teksten: [
    'Prima fundering, zegt Van der Heide. Oplevering wel pas Q3 2027.',
    'Goed bezig — nog één borrel van Hallatu verwijderd van de top.',
    'Prima loods, nog geen penthouse. Mileway zet ’m morgen in de verhuur.',
    'Van Velze tekent er zo een huurcontract voor. Wel eentje met indexatie.',
    'Draait als een machine van Camiel. Alleen de bougies nog even afstellen.',
    'Kars heeft de kleine lettertjes gecheckt: rechtsgeldig. Maar meer zat er echt niet in.',
    'De ketel brandt, zou Wessels zeggen. Kan alleen nog een graadje warmer.',
    'Prima checkpoint. Even bijladen en door naar het volgende level.',
    'Sven noteert je netjes in de notulen. Wees blij — hij vergeet weleens iemand “per ongeluk”.',
    'Begonnen als chocoladeletter, op weg naar negen ton. Blijven spelen dus!',
  ]},
  { vanaf: 40, teksten: [
    'Matig, matig… bel Jesse eens voor wat tips.',
    'Deze score is als het busje van Lust Catering: hij kwam ergens, maar niet heelhuids.',
    'Meer lucht dan inhoud. Tuf Tuf Ballonnen belt al over de rechten.',
    'Dit is het niveau van een verkiezingsbelofte. Fidel weet precies van welke partij.',
    'De Vastgoeddokter heeft de uitslag: chronisch, maar behandelbaar. Nog een potje?',
    'Garantie tot de deur. En dat terwijl Binnerts nota bene Garantiemakelaar is.',
    'Van Velze geeft deze score hooguit een flexplek. Geen vast contract.',
    'De bouwtekening was prima, zegt Duisdecker. De uitvoering… tja.',
    'Veel rook, geen vuurwerk. En geloof me: Nils kent het verschil.',
    'Zaanse zuinigheid met punten strooien — Stam knikt goedkeurend, maar meer ook niet.',
    'Volgens Kars is dit “ruim voldoende”. Maar Kars heeft ook de statuten als nachtlectuur.',
    'Banana Chaos, maar dan zonder de fun. Reflexen trainen en opnieuw!',
    'De Big Five gespot? Deze score haalt niet eens de fotorol van de Keniareis.',
    'Nieuwjaarsborrel-op-oudjaarsdag-logica: het klopt nét niet, maar gezellig is het wel.',
  ]},
  { vanaf: 20, teksten: [
    'Tsjonge jonge, wat een drama — zo laag als de rente bij de ING.',
    'Au. Je punten lekken weg als een cv-ketel van Wessels.',
    'De top 3? Die is Miles away.',
    'Zo wordt het niks. Vraag Bremer even om een donatie voor extra bonuspunten.',
    'Complete black-out. En die stond níet in het lichtplan van Nils.',
    'Door de vloer gezakt. Boudewijn kan pas over drie weken komen leggen.',
    'Van Velze heeft je score getaxeerd: leegstand.',
    'Zelfs Thijs krijgt dit niet verkocht. En die verkoopt álles.',
    'Je staat rood. Hugo blokkeert je pas uit voorzorg.',
    'Veel beloofd, niks binnengekomen — Fidel noemt dat een linkse begroting.',
    'Sven overweegt z’n lidmaatschap alwéér op te zeggen na het zien van deze score.',
    'Dit haalt de doelstelling niet. En die lag al op “minstens zes nieuwe leden”.',
    'Game over op een side quest. En de main quest moet nog beginnen…',
    'Jouw puntenoverzicht is als het jaaroverzicht van Broadcast: kort en overzichtelijk. Want leeg.',
    'De nieuwe eindbaas Joustra heeft dit gezien, hè.',
    'De spoeling is dun vanavond, zou Thijs zeggen.',
    'Zelfs Danny Vera kan deze score niet meer redden.',
  ]},
  { vanaf: 0, teksten: [
    'Wat een drama. Lijkt Patrick Stam in de sportschool wel.',
    'Total loss. Erger dan het busje van Lust Catering, en dat wil wat zeggen.',
    'Onbewoonbaar verklaard door de Vastgoeddokter. Slopen en opnieuw beginnen.',
    'Zelfs Peppi en Kokki hadden dit beter gedaan. En die moeten álles met z’n tweeën.',
    'Kars heeft ernaar gekeken: kansloos. Zelfs in hoger beroep.',
    'Erdi maakt prullenbakken voor precies dit soort scores.',
    'Hallatu schenkt er eentje in. Niet om te vieren — om te vergeten.',
    'Troostprijs: een stuk baklava van Ozgur. Die is tenminste wél zoet.',
    'Duisdecker heeft hier een vakterm voor: bouwval.',
    'Zó plat krijgt zelfs Tuf Tuf een ballon niet.',
    'Press Start, zei Van der Heide. Niet Press Stop.',
    'Sven schrijft je uit de ledenlijst. Je merkt het waarschijnlijk niet eens.',
    'Deze score valt onder “falen” uit het jaarplan. Gelukkig stond erbij: samen winnen komt later.',
    'Zelfs de anaconda van Fidel deinst hiervoor terug.',
    'Game over? Zeker niet, zou de voorzitter zeggen. Continue!',
  ]},
];
